### ISSUE TITLE
unneeded space in password credencial example

### ISSUE THREAD

**Issue by nenes25** [AdobeDocs/commerce-testing#30]
### Expected Behaviour
On the page https://developer.adobe.com/commerce/testing/functional-testing-framework/credentials/ , the sample code relative to the admin password "Add key and value pair for admin password" should be working

### Actual Behaviour
There is an unneeded space with occurs to error if we use this sample
![image](https://user-images.githubusercontent.com/7163132/215989453-37cc04c2-1993-41b2-95e9-5337a04034b7.png)

### Reproduce Scenario (including but not limited to)

run 
`vendor/bin/mftf generate:tests`

#### Platform and Version

php8.1 / Magento 2.4.5 Commerce

#### Sample Code that illustrates the problem
Issue when we have a space in the .credentials file
![image](https://user-images.githubusercontent.com/7163132/215990302-871e81a8-a8c6-4c8f-a3de-252b3fd6e52d.png)

![image](https://user-images.githubusercontent.com/7163132/215990025-8079f0b7-a69b-40af-bfaf-d158dd9dcf9f.png)

If we remove the space : 
![image](https://user-images.githubusercontent.com/7163132/215990459-99e6306a-dcc7-426f-9492-76b5c4d625e1.png)
![image](https://user-images.githubusercontent.com/7163132/215990953-853c9338-526d-47b5-8f81-c2507af47423.png)

#### Logs taken while reproducing problem
`
 ! [NOTE] Suite Data Parser Error: Password not found in credentials file magento/MAGENTO_ADMIN_PASSWORD not found. You 
 !        need to configure at least one of these options: .credentials file, HashiCorp Vault or AWS Secrets Manager    
 !        correctly and ensure key, value exists to use _CREDS in tests.                                                
 !                                                                                                                      
 !                        `

**Comment by jeff-matthews** [comment]
Thanks for the report and for the fix @nenes25!
